/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminEntrarRouteImport } from './routes/admin-entrar'
import { Route as CuidadoresRouteImport } from './routes/cuidadores'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as FamiliaEntrarRouteImport } from './routes/familia-entrar'
import { Route as ParaProfissionaisRouteImport } from './routes/para-profissionais'
import { Route as SegurancaRouteImport } from './routes/seguranca'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as AuthenticatedPainelCuidadoraRouteImport } from './routes/_authenticated/painel-cuidadora'
import { Route as AuthenticatedPainelFamiliaRouteImport } from './routes/_authenticated/painel-familia'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEntrarRoute = AdminEntrarRouteImport.update({
  id: '/admin-entrar',
  path: '/admin-entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const CuidadoresRoute = CuidadoresRouteImport.update({
  id: '/cuidadores',
  path: '/cuidadores',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const FamiliaEntrarRoute = FamiliaEntrarRouteImport.update({
  id: '/familia-entrar',
  path: '/familia-entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const ParaProfissionaisRoute = ParaProfissionaisRouteImport.update({
  id: '/para-profissionais',
  path: '/para-profissionais',
  getParentRoute: () => rootRouteImport,
} as any)
const SegurancaRoute = SegurancaRouteImport.update({
  id: '/seguranca',
  path: '/seguranca',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPainelCuidadoraRoute =
  AuthenticatedPainelCuidadoraRouteImport.update({
    id: '/painel-cuidadora',
    path: '/painel-cuidadora',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPainelFamiliaRoute =
  AuthenticatedPainelFamiliaRouteImport.update({
    id: '/painel-familia',
    path: '/painel-familia',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-entrar': typeof AdminEntrarRoute
  '/cuidadores': typeof CuidadoresRoute
  '/entrar': typeof EntrarRoute
  '/familia-entrar': typeof FamiliaEntrarRoute
  '/para-profissionais': typeof ParaProfissionaisRoute
  '/seguranca': typeof SegurancaRoute
  '/termos': typeof TermosRoute
  '/painel-cuidadora': typeof AuthenticatedPainelCuidadoraRoute
  '/painel-familia': typeof AuthenticatedPainelFamiliaRoute
  '/auth/callback': typeof AuthCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-entrar': typeof AdminEntrarRoute
  '/cuidadores': typeof CuidadoresRoute
  '/entrar': typeof EntrarRoute
  '/familia-entrar': typeof FamiliaEntrarRoute
  '/para-profissionais': typeof ParaProfissionaisRoute
  '/seguranca': typeof SegurancaRoute
  '/termos': typeof TermosRoute
  '/painel-cuidadora': typeof AuthenticatedPainelCuidadoraRoute
  '/painel-familia': typeof AuthenticatedPainelFamiliaRoute
  '/auth/callback': typeof AuthCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/admin-entrar': typeof AdminEntrarRoute
  '/cuidadores': typeof CuidadoresRoute
  '/entrar': typeof EntrarRoute
  '/familia-entrar': typeof FamiliaEntrarRoute
  '/para-profissionais': typeof ParaProfissionaisRoute
  '/seguranca': typeof SegurancaRoute
  '/termos': typeof TermosRoute
  '/_authenticated/painel-cuidadora': typeof AuthenticatedPainelCuidadoraRoute
  '/_authenticated/painel-familia': typeof AuthenticatedPainelFamiliaRoute
  '/auth/callback': typeof AuthCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-entrar'
    | '/cuidadores'
    | '/entrar'
    | '/familia-entrar'
    | '/para-profissionais'
    | '/seguranca'
    | '/termos'
    | '/painel-cuidadora'
    | '/painel-familia'
    | '/auth/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin-entrar'
    | '/cuidadores'
    | '/entrar'
    | '/familia-entrar'
    | '/para-profissionais'
    | '/seguranca'
    | '/termos'
    | '/painel-cuidadora'
    | '/painel-familia'
    | '/auth/callback'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/admin-entrar'
    | '/cuidadores'
    | '/entrar'
    | '/familia-entrar'
    | '/para-profissionais'
    | '/seguranca'
    | '/termos'
    | '/_authenticated/painel-cuidadora'
    | '/_authenticated/painel-familia'
    | '/auth/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRoute: typeof AdminRoute
  AdminEntrarRoute: typeof AdminEntrarRoute
  CuidadoresRoute: typeof CuidadoresRoute
  EntrarRoute: typeof EntrarRoute
  FamiliaEntrarRoute: typeof FamiliaEntrarRoute
  ParaProfissionaisRoute: typeof ParaProfissionaisRoute
  SegurancaRoute: typeof SegurancaRoute
  TermosRoute: typeof TermosRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-entrar': {
      id: '/admin-entrar'
      path: '/admin-entrar'
      fullPath: '/admin-entrar'
      preLoaderRoute: typeof AdminEntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuidadores': {
      id: '/cuidadores'
      path: '/cuidadores'
      fullPath: '/cuidadores'
      preLoaderRoute: typeof CuidadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/familia-entrar': {
      id: '/familia-entrar'
      path: '/familia-entrar'
      fullPath: '/familia-entrar'
      preLoaderRoute: typeof FamiliaEntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/para-profissionais': {
      id: '/para-profissionais'
      path: '/para-profissionais'
      fullPath: '/para-profissionais'
      preLoaderRoute: typeof ParaProfissionaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seguranca': {
      id: '/seguranca'
      path: '/seguranca'
      fullPath: '/seguranca'
      preLoaderRoute: typeof SegurancaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/painel-cuidadora': {
      id: '/_authenticated/painel-cuidadora'
      path: '/painel-cuidadora'
      fullPath: '/painel-cuidadora'
      preLoaderRoute: typeof AuthenticatedPainelCuidadoraRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel-familia': {
      id: '/_authenticated/painel-familia'
      path: '/painel-familia'
      fullPath: '/painel-familia'
      preLoaderRoute: typeof AuthenticatedPainelFamiliaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedPainelCuidadoraRoute: typeof AuthenticatedPainelCuidadoraRoute
  AuthenticatedPainelFamiliaRoute: typeof AuthenticatedPainelFamiliaRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedPainelCuidadoraRoute: AuthenticatedPainelCuidadoraRoute,
  AuthenticatedPainelFamiliaRoute: AuthenticatedPainelFamiliaRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRoute: AdminRoute,
  AdminEntrarRoute: AdminEntrarRoute,
  CuidadoresRoute: CuidadoresRoute,
  EntrarRoute: EntrarRoute,
  FamiliaEntrarRoute: FamiliaEntrarRoute,
  ParaProfissionaisRoute: ParaProfissionaisRoute,
  SegurancaRoute: SegurancaRoute,
  TermosRoute: TermosRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
