GRANT SELECT, INSERT, UPDATE, DELETE ON public.profiles TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.verificacoes TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.documentos TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.contratos TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.conversas TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.mensagens TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.mensagens_conversa TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.propostas TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.alertas_plantao TO authenticated;
GRANT SELECT ON public.user_roles TO authenticated;
GRANT SELECT ON public.admin_auditoria TO authenticated;
GRANT ALL ON public.profiles, public.verificacoes, public.documentos, public.contratos, public.conversas, public.mensagens, public.mensagens_conversa, public.propostas, public.alertas_plantao, public.user_roles, public.admin_auditoria TO service_role;
GRANT EXECUTE ON FUNCTION public.has_role(uuid, app_role) TO authenticated, service_role;
GRANT USAGE ON SCHEMA public TO anon, authenticated, service_role;